### ISSUE TITLE
Adding an actor to a new film causes error message

### ISSUE THREAD

**Issue by IVIvk** [IVIvk/Oscar#26]
**Issue** 
Adding an actor to a new film, causes and error message ("geen acteur geselecteerd") This is possibly due to the film not being inside the database yet.

**Workaround**
First add the film and then add the actor.

**Comment by IVIvk** [comment]
The cause was that the link between actor and film gets inserted when the admin pressed the "Acteur toevoegen" button. This action requires a FilmId, which does not yet exist. The link should only be inserted when the film is actually inserted into the database.

1/ Admin arrives in the EditFilm page (New film)
2/ Admin selects an actor and adds it to the Actor ListView
3/ Admin clicks on Film toevoegen
4/ Film is inserted into the database
5/ Link between actor and film is inserted using the FilmId.

**Comment by Total1880** [comment]
When admin adds or deletes an actor, it is saved in a List. Only when admin clicks on "film toevoegen" or "film aanpassen", the data is saved or deleted in the sql-database
